FROM apache/airflow:2.10.5-python3.12

COPY requirements.txt /tmp/skillsync-requirements.txt
COPY requirements-dbt.txt /tmp/skillsync-dbt-requirements.txt
COPY requirements-airflow.txt /tmp/skillsync-airflow-requirements.txt
RUN pip install --no-cache-dir \
    -r /tmp/skillsync-requirements.txt \
    -r /tmp/skillsync-dbt-requirements.txt \
    -r /tmp/skillsync-airflow-requirements.txt