table dim_location
	lineageTag: 069fd037-a0e9-46ec-a12b-77f45bff08d0

	column location_key
		dataType: string
		lineageTag: df251be6-448e-438c-928e-0b465ee7adf5
		summarizeBy: none
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 77c2bee3-fd91-4547-a898-7a44e12ca33f
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	partition dim_location = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(PowerBIExportPath & "\dim_location.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"location_key", type text}, {"location", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

